version: '3.8'

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - "8080"
    depends_on:
      - nextcloud_db
    networks:
      - app-network
    volumes:
      - nextcloud_vol:/var/www/html

  nextcloud_db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - nextcloud_db_vol:/var/lib/mysql
    networks:
      - app-network
 
  system:
    build:
      context: .
      dockerfile: ./Config/System/Dockerfile
    restart: unless-stopped
    container_name: system
    ports:
      - "5050"
    networks:
      - app-network
  
  homepage:
    build:
      context: .
      dockerfile: ./Config/System/Dockerfile
    restart: unless-stopped
    container_name: homepage
    ports:
      - "8000"
    networks:
      - app-network      


volumes:
  nextcloud_db_vol:
  nextcloud_vol: 

networks:
  app-network:
    driver: bridge