version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    container_name: nextcloud
    depends_on:
      - db_nextcloud
    networks:
      - app-network
    volumes:
      - nextcloud_data:/var/www/html

  db_nextcloud:
    image: mariadb
    restart: unless-stopped
    container_name: database_nc
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: npm
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  system:
    build:
      context: .
      dockerfile: ./Config/System/Dockerfile
    restart: unless-stopped
    container_name: system
    networks:
      - app-network
    environment:
      API: ${API}
      
  homepage:
    build:
      context: .
      dockerfile: ./Config/Homepage/Dockerfile
    restart: unless-stopped
    container_name: homepage
    networks:
      - app-network
        
        
volumes:
  db_data:
  nextcloud_data:

networks:
  app-network:
    external: true
