services:
  system:
    build:
      context: .
      dockerfile: ./Config/System/Dockerfile
    restart: unless-stopped
    container_name: system
    ports:
      - '4001:8080'
    networks:
      - app-network
    environment:
      API: ${API}
      CAPTCHA : ${CAPTCHA}
  
  homepage:
    build:
      context: .
      dockerfile: ./Config/Homepage/Dockerfile
    restart: unless-stopped
    container_name: homepage
    ports:
      - '4002:8080'
    networks:
      - app-network
    environment:
      API: ${API}

networks:
  app-network:
    external: true