services:
  system:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    restart: unless-stopped
    container_name: system
    networks:
      - app-network
    environment:
      - API=${API}
      - CAPTCHA=${CAPTCHA}
    ports:
      - '4001:8080'

networks:
  app-network:
    external: true