services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    depends_on:
      - db_nextcloud
    networks:
      - app_network
    volumes:
      - nextcloud_data:/var/www/html  # Volumen para los datos de Nextcloud
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  db_nextcloud:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tu_contraseña
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql  # Volumen para la base de datos
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app_network

  system:
    build:
      context: .
      dockerfile: ./Config/System/Dockerfile
    restart: unless-stopped
    container_name: system
    networks:
      - app_network
  
  homepage:
    build:
      context: .
      dockerfile: ./Config/System/Dockerfile
    restart: unless-stopped
    container_name: homepage
    networks:
      - app_network
        
        
volumes:
  db_data: { }          # Volumen para la base de datos
  nextcloud_data: { }   # Volumen para los datos de Nextcloud

networks:
  app_network: